name: Build, test, and upload dxtbx and DIALS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: conda-forge
        channel-priority: flexible
        python-version: ${{ matrix.python-version }}

    - name: Install mamba, boa and anaconda-client
      run: |
        conda install mamba boa anaconda-client constructor -y
        echo "$(conda info --base)/bin" >> $GITHUB_PATH

    - name: Build & test dxtbx
      run: |
        conda config --set anaconda_upload no
        cd dxtbx_recipe
        sed -i 's/python =3.9/python =${{ matrix.python-version }}/g' meta.yaml
        conda mambabuild . --python ${{ matrix.python-version }}
        mv /home/runner/pytest-report-dxtbx.html /home/runner/pytest-report-dxtbx-${{ matrix.python-version }}.html

    - name: Upload DXTBX pytest result
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report-dxtbx-${{ matrix.python-version }}
        path: /home/runner/pytest-report-dxtbx-${{ matrix.python-version }}.html

    - name: Upload dxtbx to anaconda
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
      run: |
        export CONDA_BLD_PATH=/usr/share/miniconda/conda-bld
        anaconda -t $ANACONDA_API_TOKEN upload --skip $CONDA_BLD_PATH/linux-64/dxtbx-*.tar.bz2

    - name: Build & test DIALS
      run: |
        conda config --set anaconda_upload no
        cd dials_recipe
        conda config --show channels
        sed -i 's/python =3.9/python =${{ matrix.python-version }}/g' meta.yaml
        conda mambabuild . --python ${{ matrix.python-version }} -c conda-forge
        mv /home/runner/pytest-report-dials.html /home/runner/pytest-report-dials-${{ matrix.python-version }}.html

    - name: Upload DIALS pytest result
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report-dials-${{ matrix.python-version }}
        path: /home/runner/pytest-report-dials-${{ matrix.python-version }}.html

    - name: Upload DIALS to anaconda
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
      run: |
        export CONDA_BLD_PATH=/usr/share/miniconda/conda-bld
        anaconda -t $ANACONDA_API_TOKEN upload --skip $CONDA_BLD_PATH/linux-64/dials-*.tar.bz2

    - name: Build conda installer using constructor
      run: |
        constructor ./
        mv dials-installer-*.sh dials-installer-${{ matrix.python-version }}.sh

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: conda-installer-${{ matrix.python-version }}
        path: ./dials-installer-${{ matrix.python-version }}.sh
