name: Build, test, and upload dxtbx and DIALS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: namannimmo,conda-forge,defaults
        channel-priority: flexible
        python-version: ${{ matrix.python-version }}

    - name: Install mamba, boa and anaconda-client
      run: |
        conda install mamba boa anaconda-client -y
        echo "$(conda info --base)/bin" >> $GITHUB_PATH

    - name: Build & test dxtbx
      run: |
        conda config --set anaconda_upload no
        cd dxtbx_recipe
        sed -i 's/python =3.9/python =${{ matrix.python-version }}/g' meta.yaml
        conda mambabuild . --python ${{ matrix.python-version }}

    - name: Upload dxtbx to anaconda
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
      run: |
        export CONDA_BLD_PATH=/usr/share/miniconda/conda-bld
        anaconda -t $ANACONDA_API_TOKEN upload --skip $CONDA_BLD_PATH/linux-64/dxtbx-*.tar.bz2

    - name: Build & test DIALS
      run: |
        conda config --set anaconda_upload no
        cd dials_recipe
        conda config --add channels conda-forge
        conda config --show channels
        sed -i 's/python =3.9/python =${{ matrix.python-version }}/g' meta.yaml
        conda mambabuild . --python ${{ matrix.python-version }} -c conda-forge

    - name: Upload DIALS to anaconda
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
      run: |
        export CONDA_BLD_PATH=/usr/share/miniconda/conda-bld
        anaconda -t $ANACONDA_API_TOKEN upload --skip $CONDA_BLD_PATH/linux-64/dials-*.tar.bz2
