name: Build and test dxtbx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge,defaults

    - name: Install conda-build
      run: conda install conda-build -y

    - name: Build Conda package
      run: |
        conda config --set anaconda_upload no
        cd dxtbx_recipe
        conda build .
